### PR TITLE
Chef 14 fixes

### PR DESCRIPTION
**Pull request by zakame**
This updates the cookbook to make it work on Chef 14:

- Update test-kitchen setup to be more usable and add basic usage tests
- Convert custom resources from LWRP to Chef 12.5 style
- Apply foodcritic/cookstyle fixes

### CODE REVIEW

**Comment by zakame** [comment]
@elance-rjenkins thanks, I might do that once I'm clear with the Supermarket maintainers about cookbook adoption process (since they currently only document [`knife supermarket share`](https://docs.chef.io/knife_supermarket.html#share) for adding new cookbooks.  Apparently there seems to be a [list of those available for adoption](https://supermarket.chef.io/available_for_adoption) but the `perlbrew` cookbook is not among it.

**Comment by uday3110** [comment]
@zakame  can you please merge this in master so we can use it

**Comment by zakame** [comment]
@uday3110 yes, I hope we can get this out to the supermarket soon.  I don't have write access to this repo here so we still need @jrmash to merge it :crossed_fingers: 

@jrmash I'm interested in continuing maintenance of this cookbook, if you are no longer up to it :muscle:

**Comment by zakame** [comment]
Thanks @jrmash! :tada:

**Pull request merged**
